requirements-dev.txt

Set `pytest-aiohttp` to v 0.1.3 
Set `pytest-asyncio` to v 0.5.0
Set `pytest` to v 3.0.7
I tried running the tests locally last night and they failed due to recent updates in pytest-asyncio.
The tests passed again after setting `pytest-asyncio` to version 0.5.0
Per @brettcannon's suggestion, also set the version of `pytest-aiohttp`.
Edit: A lot of warnings were generated when using `pytest` 3.1.0. ([travis log](https://travis-ci.org/python/bedevere/builds/237239682)) Setting it the version to 3.0.7

Pin the versions in requirements-dev.txt

---

bedevere/bpo.py

GitHub truncates at 50 characters through CSS. While you can hover on the text to get the whole thing, trying to keep it short since people don't always realize that hovering works.
Closes #46

Shorten bpo issue # check failure description

---

bedevere/backport.py

Sometimes when creating the backport PR, the [X.Y] prefix was not added.
If the title is edited afterwards, bedevere should then remove the backport label.
Fixes https://github.com/python/bedevere/issues/50

Remove backport label when PR is edited.

---

bedevere/__main__.py
bedevere/close_pr.py
tests/test_close_pr.py

This will close invalid PRs, so at least one less boring chore for core devs.
People in codeowners still get notified though...
A PR is considered invalid if it tries to merge `python:<maint_branch>` into `python:master`.
For example `python:3.6` into `python:master`.
Closes https://github.com/python/core-workflow/issues/168

Close PR that tries to merge maintenance branch into master

---

bedevere/stage.py
tests/test_stage.py

See https://mail.python.org/pipermail/python-committers/2017-October/004902.html and https://mail.python.org/pipermail/core-workflow/2017-October/001039.html for reference.
The old trigger phrase is left in as both an easter egg and for supporting people who have begun to use the phrase out of habit. The easter egg in the comment about the trigger phrase is untouched.

Support a more muted trigger phrase for another review

---

bedevere/stage.py
tests/test_stage.py

I noticed a few failed webhook deliveries, with delivery IDs:
e803a5f0-b3c2-11e7-88b0-b656aa65ce54
726f2a80-b390-11e7-9de2-d0a4e98e7a9f
In the payload from GitHub, it shows that `["review"]["state"]` is `"commented"`, but bedevere was expecting `"comment"`. I think that was the problem.

pull_request_review state should be `commented` instead of `comment`.

---

bedevere/close_pr.py
tests/test_close_pr.py

The regex pattern wasn't correct.
It was matching on head branch that contains only digits (e.g. 12345).

Only close invalid PRs that match Python maintenance branch patterns.

---

tests/test_stage.py

There was a dictionary at the beginning of the file that doesn't seem to be needed.

Cleanup test_stage.py

---

bedevere/stage.py
tests/test_stage.py

Follow up from [core-workflow](https://mail.python.org/mm3/archives/list/core-workflow@python.org/thread/H5CRUS6AHTTJDXWUAMJZWKXEAMMRQPM3/) email thread.
The change requested message is now shorter when PR author is a core dev:
```
When you're done making the requested changes, leave the comment:
`I have made the requested changes; please review again`
```

Make the "Change requested" message brief when PR is authored by Core Dev

---

bedevere/backport.py
tests/test_bpo.py

old | new
--- | ---
`relevent` | `relevant`
`unlabled` | `unlabeled`

Fix two typos

---

bedevere/bpo.py
tests/test_bpo.py

This came up in https://github.com/python/cpython/pull/5291
The PR did not have any description, and the title was
edited to include the bpo number.
It caused a 500 error, because bedevere did not anticipate
this situation.
Updated the code so that it takes into consideration when the
body is empty.

Fix issue where PR without any description has its title edited

---

runtime.txt

Heroku now supports Python 3.7.0.
https://devcenter.heroku.com/articles/python-runtimes

Use Python 3.7.0 in Heroku

---

tests/test_stage.py

This PR addresses Mariatta's comment in #113 regarding the addition of test cases to test the removal of all labels.
Closes https://github.com/python/bedevere/issues/113

Improve two testcases to test all labels

---

bedevere/backport.py
bedevere/news.py
tests/test_backport.py
tests/test_filepaths.py

If a PR is made not against master, check the PR title.
If the PR title does not match the backport pattern,
post a failure status.
Two ways to resolve:
- reopen the PR against master
- Update the PR title accordingly
Depends on https://github.com/python/devguide/pull/392
Closes https://github.com/python/core-workflow/issues/211
Closes https://github.com/python/bedevere/issues/111

Post a status check for backport PR title.

---

bedevere/bpo.py
tests/test_bpo.py

Hey, This aims to fix #103 .
If anything needs any improvement please hint me, I'll fix it up in the best manner I can :smile: 
(I added the changes to bpo.py, if you find it inappropriate, please suggest where it'd suite better)

Automatically hyperlink `bpo-` text. (#103)

---

bedevere/backport.py
tests/test_backport.py

Maybe with this, we can make it a required status check.
Closes https://github.com/python/bedevere/issues/124

Only check for the maintenance branch prefix.

---

bedevere/news.py
tests/test_news.py

When a PR is missing a news entry, link to blurb-it instead of devguide.

Provide link to blurb-it

---

bedevere/news.py
tests/test_news.py

From discussions in https://github.com/python/cpython/pull/11779#issuecomment-462498706, it was determined that the check news status should pass as long as the news file is not empty. cc @ned-deily

Check news will pass as long as the file is not empty.

---

.travis.yml
requirements.txt

Ref: https://github.com/travis-ci/travis-ci/issues/9069

Use the xenial dist when testing Python 3.7

---

bedevere/bpo.py
bedevere/close_pr.py
runtime.txt

We used to need to pass the `maintainer_can_modify` flag, but now we're getting error message `422 Validation Failed for 'maintainer_can_modify'` when patching the PR. (to append the bpo link)
Removing the `maintainer_can_modify` flag fixes the problem, I tested in command line.
Hopefully this quick fix can unblock people.
Perhaps something changed from GitHub side, but I'm not seeing anything obvious in [their changelog](https://github.blog/changelog/).
Closes #162 
Closes https://github.com/python/core-workflow/issues/321

Don't pass `maintainer_can_modify` when patching the PR.

---

bedevere/__main__.py
requirements.txt

Add sentry

---

.travis.yml

Technically we're running it in 3.7+

Remove test against 3.6 in .travis.yml

---

bedevere/bpo.py
tests/test_bpo.py

Also includes minor code cleanup.
Fixes #164.

Avoid putting new bpo links inside of existing links

---

bedevere/backport.py
tests/test_backport.py

Creating label is boring. With this PR, bedevere will automatically
create the `needs backport to ` label when a maintenance branch
is created under CPython repo.
Maintenance branch has the pattern: 3.9, 4.0, 3.10, ...

Automatically create "needs backport to" label when maintenance branch created.

---

README.md

I am a student of python and was looking through the code on github. 
I chose to fix the link to the witch sketch on Youtube so that the background of Bedevere can be better understood.
The [Old Link](https://youtu.be/k3jt5ibfRzw) does not work anymore.

Changed the link to the witch scene on youtube

---

bedevere/stage.py

After #158 has been merged, the state machine graph was out of date.
This update fixes the transition from "New PR" for core developers to
"Awaiting core review" instead of "Awaiting merge".

Fix PR state machine graph

---

bedevere/stage.py
tests/test_stage.py

Upon changing the status to `awaiting change review`, a review is also requested through the new GitHub API from the appropriate reviewers.
#165

Request review on GitHub when the PR needs change review

---

bedevere/stage.py

As the video references to jokes from Monty Python are continually removed from YouTube, the links to those videos are removed.
Fixes #201

Removing Monty Python joke refference links.

---

bedevere/stage.py
tests/test_stage.py

If an approval comes after the PR has been merged, bedevere still
applies the `awaiting merge` label, which might cause confusion
when searching for PRs with that label.
Fixes #291.

Do not apply the 'awaiting merge' label on a closed PR

---

runtime.txt

In #309 I've added Python 3.9 and Python 3.9-dev to the CI job, and disallowed failure on those versions.
Closes #280

Use Python 3.9.1

---

pytest.ini

`filterwarnings` with extra warning types might be problematic, because it can hide some important messages in the future.
I've checked that right now there are no warnings (and no point in keeping it):
- 3.8: https://github.com/sobolevn/bedevere/runs/5302010464?check_suite_focus=true#step:7:29
- 3.9: https://github.com/sobolevn/bedevere/runs/5302010520?check_suite_focus=true#step:7:29
- 3.10: https://github.com/sobolevn/bedevere/runs/5302010602?check_suite_focus=true#step:7:29
Docs about new `asyncio-mode` setting: https://github.com/pytest-dev/pytest-asyncio#modes

Remove unused `filterwarnings` from `pytest.ini`

---

bedevere/prtype.py
tests/test_filepaths.py
tests/test_prtype.py

Closes https://github.com/python/core-workflow/issues/432

Use the new "type" labels after GH migration.

---

.github/workflows/ci.yml

Changes:
1. Updates `codecov` version to the latest one
2. Fixes cache key, it should include both `txt` files (`'pyproject.toml'` does not exist) and python version

Improve `ci.yml`

---

bedevere/news.py
tests/test_news.py

Blurb generates gh-issue- but Bedevere only accepted gh-. This was discussed here: https://github.com/python/core-workflow/pull/431#discussion_r827293459

Fix gh-issue- prefix

---

.github/workflows/ci.yml

Updates PR https://github.com/python/bedevere/pull/399 using workarounds from https://github.com/python/bedevere/pull/399#issuecomment-1073356616.

Workaround to fix Python 3.11

---

bedevere/gh_issue.py
tests/test_gh_issue.py

Those generate BPO URLs that redirect back to Github. Tests updated.
Closes #426.

Restore support for "bpo-XXX: title" headers

---

.github/.codecov.yml

Delete the `comment: true` from the YAML to hopefully workaround a Codecov bug and enable commenting on this repo.
As suggested in https://github.com/python/bedevere/issues/441#issuecomment-1110357378

Delete .codecov.yml and "comment: true"

---

bedevere/news.py

Bedevere's comment is slightly misleading ([for example](https://github.com/python/cpython/pull/92121#issuecomment-1114957171
)):
> Every change to Python [requires a NEWS entry](https://devguide.python.org/committing/#updating-news-and-what-s-new-in-python).
> 
> Please, add it using the [blurb_it](https://blurb-it.herokuapp.com) Web app or the [blurb](https://pypi.org/project/blurb/) command-line tool.
Bedevere's link to the devguide begins:
> Almost all changes made to the code base deserve an entry in `Misc/NEWS.d`.
And then details the exceptions.
Let's update Bedevere's comment to say "Almost every change ..." instead of "Every change ...".

Update comment: *almost* every change needs a NEWS entry

---

README.md

Like other https://github.com/python repos, shall we rename the `master` branch to `main`?
An admin needs to do the rename at https://github.com/python/bedevere/settings/branches
This PR is the only code change in the repo.

Rename `master` to `main`

---

CONTRIBUTING.rst

Add instructions for maintainers on how to deploy bedevere manually.
We need this until the GitHub <--> Heroku integration is resolved.

Add contributing and maintenance guide

---

.github/workflows/ci.yml

Fixes https://github.com/python/bedevere/issues/462.
Re: https://github.com/python/bedevere/issues/462#issuecomment-1141391471
Two things here.
First add `-cov-report=term` to pytest, so we get output like this for 3.11 and can see coverage is missing (and 100% with 3.8-3.10):
```
Name                      Stmts   Miss Branch BrPart  Cover
-----------------------------------------------------------
bedevere/__init__.py          0      0      0      0   100%
bedevere/__main__.py         37      0      4      1    98%
bedevere/backport.py         63      0     36      0   100%
bedevere/close_pr.py         22      0     14      0   100%
bedevere/filepaths.py        15      0     12      0   100%
bedevere/gh_issue.py         72      0     34      1    99%
bedevere/news.py             51 …
```

Use Python version as flag for Codecov

---

.github/workflows/ci.yml

https://github.com/actions/setup-python now has pip caching built-in: https://github.com/actions/setup-python#caching-packages-dependencies
So we don't an extra https://github.com/actions/cache step.
We also don't need to install Coverage.py explicitly, as we're using pytest-cov (via dev-dependencies.txt) that takes care of it.

CI: Use actions/setup-python to cache pip

---

.github/workflows/ci.yml
pytest.ini
tox.ini

Fixes #469.
- Add tox.ini from jaraco/skeleton
- Trim irrelevant details from tox.ini
- In CI, invoke tests with tox. Move pytest args to pytest config.

Add tox config and build using CI

---

.github/workflows/ci.yml
tox.ini

After I pushed the tox changes (https://github.com/python/bedevere/pull/471, https://github.com/python/bedevere/pull/474) to my branch, it failed on Python 3.11:
* https://github.com/hugovk/bedevere/runs/6969338848?check_suite_focus=true
But it passed here:
* https://github.com/python/bedevere/actions/runs/2529801953
The problem is we are missing the env vars to temporarily fix the dependency build for 3.11. Let's move them out of the workflow and into tox.ini, so they're also available locally.
The reason it passed here was because there was still a pip cache from last time, whereas the cache had expired on my fork and it needed to build again from scratch.
Here's a passing run of this fix on my fork:
* https://github.com/hugovk/bedevere/actions/runs/2529924094
---
Also keep the colour …

Set env vars in tox to build 3.11 dependencies

---

bedevere/backport.py
tests/test_backport.py

gh-381: Add test and fix when base branch isn't a maintenance branch.

---

bedevere/prtype.py
tests/test_filepaths.py
tests/test_prtype.py

Refactor as requested by @ezio-melotti in https://github.com/python/bedevere/pull/485#discussion_r916157446.
Also couldn't help but notice the unused import so I removed it in a separate commit. If that's undesired I'll revert that change obviously!

Refactor ``Category`` to be ``Labels``

---

bedevere/prtype.py
bedevere/util.py
tests/test_filepaths.py
tests/test_prtype.py

Closes #457.
Also closes https://github.com/python/core-workflow/issues/363.
Follow up can also tackle https://github.com/python/core-workflow/issues/421 but I decided to keep this small since the feedback on https://github.com/python/core-workflow/issues/363 shows that the consensus reached in #457 is not shared by everybody.
Two edge cases which were not considered in the original issue but on which somebody should probably take a decision:
1) What if the PR already has a news item? Currently it still adds the `skip news` label as shown by `test_docs_and_news`.
2) Should the `skip news` label also be applied if the PR has a test? Currently I thought I would not do so as to not make this change too controversial, but I'm happy to change this obviously.
Let me know what you think!

Auto add the ``skip news`` label to ``docs`` PRs

---

bedevere/filepaths.py
bedevere/prtype.py
tests/test_filepaths.py

Follow up to https://github.com/python/bedevere/pull/485
https://github.com/python/cpython/pull/94828 shows the previous PR works: changes to documentation are correctly labeled as `skip news`.
However, we're doing the check for the `blurb_it` help comment before we do the labeling.
This makes it so that we don't check whether we need to post that comment if we are going to label a PR as skip news.
/CC @ezio-melotti

Label a PR before posting the blurb help comment

---

README.md
bedevere/stage.py

This PR adds a flowchart that describe the PR state machine to the `README`.  
Related issues:
* The flowchart will be linked in https://github.com/python/devguide/pull/930
* The idea was brought up in https://github.com/python/devguide/issues/868
The flowchart is described in
https://github.com/python/bedevere/blob/428290e46a9507c7810614e15294163d2b4f9eb0/bedevere/stage.py#L3-L38
which renders to
For the implementation I used mermaid, which is supported natively by GitHub-flavored Markdown.  The new flowchart renders to:
```mermaid
flowchart TD
A([New PR]):::creator
A -- by contributor --> B[Awaiting review]:::anyone
A -- by core dev --> C[Awaiting core review]:::coredev
B & C -- new review by\nanother contributor --> C
C & B & E  -- new core review\nrequests changes --> D[Awaiting …
```

Add the labels flowchart to the README.

---

.github/workflows/ci.yml
requirements.txt
tox.ini

Bump dependencies now they support Python 3.11 and remove the workarounds.

Remove Python 3.11 test workarounds

---

bedevere/gh_issue.py
tests/test_gh_issue.py

Closes #468.
This check should be done before we get any other information.
I had to change some test data because they were "incomplete". I could also check for the label on the old lines 52-54, but then we would unnecessarily validate the issue number we found in the title. Thought it made more sense to do it like this.

Do not fail issue number test for all PRs with ``skip issue`` label

---

bedevere/backport.py
tests/test_backport.py

Closes https://github.com/python/bedevere/issues/440.
The `if ... return` makes it so we never comment if there original PR doesn't have a back port label.

Comment about a backport even if the original PR doesn't have a label

---

.github/workflows/ci.yml

The matrix factor for the Python version is imprecise and doesn't always contain characters suitable for Codecov flags. `actions/setup-python@v4` now provides an output specifying exactly what's been installed based on the request. This value is perfect for use in flags. This patch implements just that.

Use actual precise Python version @ coverage flags

---

bedevere/gh_issue.py
bedevere/util.py
tests/test_gh_issue.py
tests/test_util.py

closes https://github.com/python/bedevere/issues/501

Add Pull Request Link to Issue

---

bedevere/gh_issue.py
bedevere/util.py
tests/test_gh_issue.py
tests/test_util.py

closes https://github.com/python/bedevere/issues/517

Add PR Links as Task List Items to Issues

---

bedevere/util.py
tests/test_gh_issue.py
tests/test_util.py

Follow up of my conversation with @ezio-melotti.
> Looks like this is not working for multiple PRs (https://github.com/python/cpython/issues/96192). After some investigation I found that `tasklists` doesn't just render the new UI, it also re-writes the Issue body.
> 
> **Example:**
> 
> ```markdown
> 
> 
> https://github.com/python/cpython/issues/96192#tasklist-block-8fd60492-131e-4b4a-abab-06800aa4bb11
> 
> 
> 
> 
> 
> 
> https://github.com/python/cpython/issues/96192#tasklist-block-ea9583fe-18a8-47ee-aec9-08a62427146b
> 
> 
> ```
> 
> I found this after I inspected the API response for https://github.com/python/cpython/issues/96192 (https://api.github.com/repos/python/cpython/issues/96192). This did not happen for the repositories I tested this PR on because it did not have this feature …

Add PR Links as List Items to Issues

---

requirements.txt

The py library is no longer a (transitive) dependency, let's remove it from requirements.txt.

Remove unused py dependency

---

.github/workflows/ci.yml

Similar to https://github.com/python/blurb_it/pull/331.
Let's pin to alpha 4 to the CI green and at least have some level 3.12 testing.
Upstream issues:
See also notes at https://github.com/python/blurb_it/pull/330#issuecomment-1449496275.

Temporarily pin to 3.12.0a4 pending dependency support for a5+

---

bedevere/backport.py
tests/test_backport.py

No longer need to update the `ALLOWED_BRANCHES` list in the CPython emailer webhook

Remove unneeded codepath

---

.github/workflows/ci.yml
dev-requirements.txt

The `codecov` package is no longer installable, meaning that `pip install dev-requirements.txt` for this repo now always fails. It also doesn't seem to be necessary to install it in CI; we don't use it for anything as far as I can see, and the codecov action doesn't require it.

Remove codecov dependency; skip running CI on 3.12 for now

---

.github/workflows/ci.yml

With `fail-fast` set to True (the default), all running jobs in the matrix are cancelled as soon as a single one fails. This makes it hard to see exactly which Python versions a PR is failing on, if there are failures, because the CI just becomes a sea of red, even if the PR is only failing on a single Python version.

CI: set `fail-fast` to False

---

README.md
bedevere/stage.py
tests/test_stage.py

1. if opened PR is draft - don't add labels
2. if draft PR is published - add labels as a new non-draft PR
3. if a PR is unpublished - clear labels

gh-554: Handle Draft PRs

---

bedevere/stage.py
tests/test_stage.py

gh-555 introduced the PR edited handler to handle draft PRs. The implementation was over-reaching, and triggered on any edited events (including renaming PR). This PR fixes that by removing the PR-edited handler and replacing it with two more specific handlers that more narrowly match the original intent, namely, respond to changes in the draft state of the PR (publish / unpublish).
Fixes gh-556

gh-556: Fix over-reaching PR-edited event handler

---

.github/workflows/ci.yml

Fix for the new tox 4.10.0 release (4.11.0 is now the newest):
```
Run tox
tox
shell: /usr/bin/bash -e {0}
env:
FORCE_COLOR: 1
pythonLocation: /opt/hostedtoolcache/Python/3.10.12/x64
PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.12/x64/lib/pkgconfig
Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.12/x64
Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.12/x64
Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.12/x64
LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.12/x64/lib
TOXENV: python
ROOT: HandledError| provided environments not found in configuration file:
python
Error: Process completed with exit code 254.
```
https://github.com/python/bedevere/actions/runs/6047954379/job/16412393623?pr=578
We use `pyXXX` in `tox.ini`:
```ini
envlist = py{312, 311, 310, 39, 38}
``` …

CI: Specify tox 'py' environment

---

.github/workflows/ci.yml
requirements.txt

X-ref https://github.com/aio-libs/aiohttp/issues/7675

Test with Python 3.12 in CI

---

bedevere/__main__.py

It is not needed anymore after the conversion to GitHub App.

Remove the use of GitHub OAuth Token

---

bedevere/news.py

The existing message did not cover the option of skipping the entry with `skip news`, which can result in unnecessary work being done by new contributors.
Resolves #590

Tweak the language for the help text

---

bedevere/__main__.py
bedevere/stage.py
tests/test_stage.py

This reverts commit 72090a4a0e960f307b37e6064bf7b71e36fa1414.

Revert "Add logging to debug bedevere label staging (#594)"

---

bedevere/prtype.py
bedevere/util.py
tests/test_prtype.py

Add the "docs" label also for Doc/*/.nitignore

---

bedevere/prtype.py
tests/test_prtype.py

Add the "tests" label also for files, starting with "_test"

---

bedevere/news.py

The old link still works and redirects to the new one, but let's link directly to the new place.

Update redirected link

---

bedevere/news.py

Remove unnecessary `index.html` from link.

---

.github/workflows/ci.yml
bedevere/gh_issue.py
bedevere/util.py
tox.ini

https://devguide.python.org/versions/

Drop support for EOL Python 3.8

---

.github/workflows/ci.yml
.github/workflows/lint.yml

Like https://github.com/python/blurb/pull/32.
Tests:
* No cache: [2m 29s](https://github.com/hugovk/bedevere/actions/runs/11645308822/usage) -> [1m 57s](https://github.com/hugovk/bedevere/actions/runs/11645334667/usage)
* With cache: [2m 15s](https://github.com/hugovk/bedevere/actions/runs/11645345451/usage) -> [1m 58s](https://github.com/hugovk/bedevere/actions/runs/11645346035/usage)
Lint:
* We had a pre-commit config file but weren't running on the CI before. Let's add it.
Also:
* Fix https://github.com/woodruffw/zizmor findings (the `persist-credentials: false`).

CI: Lint and test via uv

---

bedevere/prtype.py
tests/test_prtype.py

Add docs label for markdown files

---

README.md

* Fix line breaks (`\n` is not supported)
* Fix arrow colors

Fix diagram in `README.md`
