- bedevere/bpo.py
- tests/test_bpo.py
Fixes https://github.com/python/bedevere/issues/4
> Link to b.p.o when both issue number and trivial label are found

- bedevere/__main__.py
- bedevere/backport.py
- requirements.txt
- tests/test_backport.py
> Automatically remove backport labels

- bedevere/__main__.py
- bedevere/backport.py
- tests/test_backport.py
- tests/test_bpo.py
> Fix dispatching of the backport module

- bedevere/bpo.py
- tests/test_bpo.py
Not to be merged until:
Partial work for https://github.com/python/bedevere/issues/25
> Check "skip issue" instead of "trivial" label

- bedevere/bpo.py
No other services do that so it stands out as looking a little odd.
> Drop periods from status description

- bedevere/bpo.py
textwrap.dedent() just was not doing the right thing.
> Fix the body replacement code

- bedevere/news.py
- tests/test_news.py
> Take the 'next' directory into account

- bedevere/stage.py
- tests/test_stage.py
> Touch up the change review notification

- bedevere/stage.py
Don't worry about mentioning a specific core dev and don't use hard line breaks.
> Tweak the "changes requested" message

- bedevere/backport.py
- bedevere/stage.py
- bedevere/util.py
- tests/test_stage.py
> Don't leave another "changes requested" comment if already awaiting changes

- bedevere/news.py
- tests/test_news.py
> Better failure messages for news entries

- bedevere/stage.py
- tests/test_stage.py
> Completely ignore comment reviews from stage decisions

- bedevere/backport.py
- tests/test_backport.py
> Copy labels from parent PR to backport PR(s)

- bedevere/follow_up.py
- tests/test_follow_up.py
To address number 2 of https://github.com/python/bedevere/issues/14
If a PR was merged and the commit message was not changed from `#NNNN` to `GH-NNNN`, bedevere-bot will leave a comment to remind core dev to update it next time.
For example:
`@Mariatta: Please replace # with GH- in the commit message next time. Thanks!`
> Remind core dev to replace # into GH- in the commit message.

- bedevere/bpo.py
- tests/test_bpo.py
Fixes https://github.com/python/bedevere/issues/90
> Don't add "None" when PR body is empty.

- runtime.txt
Previously it was set to 3.6.1.
> Set Heroku runtime environment to Python 3.6.4

- bedevere/close_pr.py
- tests/test_close_pr.py
Fixes https://github.com/python/bedevere/issues/69
> Dismiss review request from invalid PRs.

- .gitignore
- pytest.ini
- requirements.txt
- tests/test___main__.py
> Adopt to aiohttp 3.0

- .gitignore
- bedevere/backport.py
- tests/test_backport.py
Accept leading spaces and having other parentheses somewhere in the title.
Closes #95
> Be more tolerant of title formats

- bedevere/bpo.py
- bedevere/filepaths.py
- tests/test_bpo.py
- tests/test_news.py
Closes https://github.com/python/bedevere/issues/117
> Check for news entry and bpo number when PR is reopened.

- tests/test_news.py
https://github.com/brettcannon/gidgethub/blob/b5c3c2f14b61c65c99fd523ae6e9dbf45876728a/gidgethub/sansio.py#L78
My IDE complained.. 😝
> The delivery_id argument gidgethub.sansio.event should be a `str`.

- bedevere/filepaths.py
- bedevere/news.py
- bedevere/util.py
- tests/test_filepaths.py
- tests/test_news.py
Closes https://github.com/python/bedevere/issues/127
> News status: Only post success status if news entry is at least 30 characters.

- bedevere/bpo.py
- tests/test_bpo.py
This pull request resolves issue #133
> Fix link to bugs.python.org

- bedevere/close_pr.py
- tests/test_close_pr.py
Leave a comment that the PR is invalid.
Add Invalid label, so it doesn't count towards Hacktoberfest.
Closes https://github.com/python/bedevere/issues/137
> Invalid PRs: leave comment and add "invalid" label.

- bedevere/stage.py
- tests/test_stage.py
> Apply 'awaiting core review' label to new core-dev PRs

- bedevere/bpo.py
- tests/test_bpo.py
As proposed by @Mariatta in #146.
> Linkify bpo mentions in commit comments

- tests/test_stage.py
This is a specific test case for #139.
This should be the enough to consider the issue resolved by #157.
> Add test case (non-core dev review)

- bedevere/bpo.py
- tests/test_bpo.py
> Explicitly require 'session' objects to be passed into set_status()

- bedevere/stage.py
Fixes for #184 
Please review the changes
Is it too verbose?
Thank you!
Edit1: Added graphviz image
> Added verbose edge labels and new edge color for triager actions

- runtime.txt
> Use Python 3.7.5 runtime

- bedevere/stage.py
- bedevere/util.py
- tests/test_stage.py
- tests/test_util.py
Before deployment:
Closes https://github.com/python/core-workflow/issues/325
> Re-request core review when there is a new commit to the approved PR

- runtime.txt
> Use Python 3.8.3 runtime

- runtime.txt
> Bump the Python runtime environment to 3.8.5

- runtime.txt
Closes https://github.com/python/bedevere/issues/276
> Update to 3.8.6 runtime

- bedevere/backport.py
- bedevere/close_pr.py
- tests/test_backport.py
- tests/test_close_pr.py
> Account for the renaming of the 'master' branch to 'main'

- .coveragerc
- bedevere/util.py
Fail the CI if it's not 100% coverage
> Add .coveragerc file

- .github/codecov.yml
Fixes https://github.com/python/bedevere/issues/441.
Following suggestion at https://github.com/python/bedevere/issues/441#issuecomment-1112871092
> Codecov: keep some 'comment' value to override global YAML

- bedevere/news.py
> Fix grammar in Bedevere's message about NEWS entries

- .github/workflows/ci.yml
Fixes https://github.com/python/bedevere/pull/471#issuecomment-1160538865.
Docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#env
> Fix workflow syntax

- README.md
- bedevere/gh_issue.py
The existing links were broken.
> Fix links to Lifecycle of a Pull Request: Submitting

- README.md
- bedevere/stage.py
- tests/test_stage.py
Closes https://github.com/python/bedevere/issues/269
Also removed two unused imports.
> Update stage based on dismissed reviews

- .github/workflows/ci.yml
- tox.ini
Same as:
* https://github.com/python/blurb_it/pull/316
> Update Python versions in the CI workflow.

- .github/dependabot.yml
* Add `github-actions` ecosystem
* Remove obsolete ignores
* Reformat file
> Update `dependabot.yml` to include `github-actions`

- bedevere/backport.py
- tests/test_backport.py
The color should not include the leading #
Fixes https://github.com/python/bedevere/issues/560
Doc: https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#create-a-label
> Fix label creation

- bedevere/backport.py
- tests/test_backport.py
Add the label description upon creation.
> Update label creation

- .git-blame-ignore-revs
- .pre-commit-config.yaml
- CONTRIBUTING.rst
- bedevere/__main__.py
- bedevere/backport.py
- bedevere/close_pr.py
- bedevere/filepaths.py
- bedevere/gh_issue.py
- bedevere/news.py
- bedevere/prtype.py
- bedevere/stage.py
- bedevere/util.py
- tests/test___main__.py
- tests/test_backport.py
- tests/test_close_pr.py
- tests/test_filepaths.py
- tests/test_gh_issue.py
- tests/test_news.py
- tests/test_prtype.py
- tests/test_stage.py
- tests/test_util.py
This would make the codebase formatting consistent and help avoid discussions about the formatting on PRs.
> Add linting and auto-formatting via pre-commit

- bedevere/backport.py
- tests/test_backport.py
> Copy over topic-* labels to backport PRs

- .github/workflows/ci.yml
- tox.ini
Currently in alpha:
* https://devguide.python.org/versions/
* https://peps.python.org/pep-0745/
> Test Python 3.14
